### ISSUE TITLE
This doesn't look correct to me

### ISSUE THREAD

**Issue by AdityaSoni19031997** [abhishekkrthakur/wtfml#1]
https://github.com/abhishekkrthakur/wtfml/blob/7ca228a7a171a8ff4d9ddb291c56809aebfc0f4a/wtfml/engine/engine.py#L40-L41

**Comment by abhishekkrthakur** [comment]
Please feel free to fix via a PR. :)

**Comment by AdityaSoni19031997** [comment]
Please feel free to close the issue; Jokes Apart! You are aware of the scenario i feel, hence closing it;
