### ISSUE TITLE
Gpu Unpack

### ISSUE THREAD

**Issue by JOHNFFFEE** [abhishekkrthakur/wtfml#2]
Hi Abishek, 
The image dataloader is not compatible with GPU, there is a  cannot unpack non-iterable object issue
Thanks for your help

**Comment by abhishekkrthakur** [comment]
weird. it works fine with GPU. Could you please post the full stacktrace?

**Comment by JOHNFFFEE** [comment]
https://www.kaggle.com/parlin987p/melanoma-detection-part-1

**Comment by abhishekkrthakur** [comment]
Could you please use the stable version? I have started modifying the code a lot. :) 

pip install wtfml==0.0.2

**Comment by JOHNFFFEE** [comment]
done, it is working.
I will take a look for the change
thanks
